name: pdf_reader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  file_picker: ^10.1.9
  easy_localization: ^3.0.7
  google_fonts: ^6.2.1
  syncfusion_flutter_pdfviewer: ^29.1.33
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.0
  timezone: ^0.10.0
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0     

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  collection: ^1.19.1
  http_parser: ^4.1.2
  material_color_utilities: ^0.13.0
  string_scanner: ^1.3.0
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.8
  test_api: ^0.7.3
  win32_registry: ^2.1.0
  meta: ^1.16.0
  permission_handler_platform_interface: ^4.2.3

flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/translations/
  - assets/imgs/
  - assets/icons/
